version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy/SweetClub
    overwrite: yes

permissions:
  - object: /home/ubuntu/deploy/SweetClub
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 300
