version: "3.8"
services:
  nginx:
    image: timssuh/sweetclub-nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - front
      - back

  front:
    image: timssuh/sweetclub-front
    restart: always
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 4000

  back:
    image: timssuh/sweetclub-back
    restart: always
    env_file:
      - ./back/.env
    # environment:
    #   BACK_PORT: $BACK_PORT
    #   COOKIE_SECRET: $COOKIE_SECRET
    #   DB_USERNAME: $DB_USERNAME
    #   DB_PASSWORD: $DB_PASSWORD
    #   DB_DATABASE: $DB_DATABASE
    #   DB_PORT: $DB_PORT
    #   DB_HOST: $DB_HOST
    #   JWT_ACCESS_SECRET: $JWT_ACCESS_SECRET
    #   JWT_ACCESS_EXPIRY_TIME: $JWT_ACCESS_EXPIRY_TIME
    #   JWT_REFRESH_SECRET: $JWT_REFRESH_SECRET
    #   JWT_REFRESH_EXPIRY_TIME: $JWT_REFRESH_EXPIRY_TIME
    #   REDIS_HOST: $REDIS_HOST
    #   REDIS_PORT: $REDIS_PORT
    #   REDIS_PASSWORD: $REDIS_PASSWORD
