name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Build back test
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./back
          file: ./back/Dockerfile.dev
          push: false
          tags: sweetclub-back-test
          load: true

      - name: back test
        run: docker run sweetclub-back-test npm run test

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push back
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./back
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sweetclub-back

      - name: Build and push front
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./front
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sweetclub-front

      - name: Build and push nginx
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./nginx
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sweetclub-nginx
