# This is a basic workflow to help you get started with Actions

name: Build and Push Docker Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Docker Login
        uses: docker/login-action@v1.14.1
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
         
      - name: Build and push back
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./back
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sweetclub-back
          
      - name: Build and push front
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./front
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sweetclub-front
          
      - name: Build and push nginx
        uses: docker/build-push-action@v2.10.0
        with:
          context: ./nginx
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sweetclub-nginx
    
